// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Add: typeof import('./components/Add.vue')['default']
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonMoon: typeof import('~icons/carbon/moon')['default']
    CarbonSun: typeof import('~icons/carbon/sun')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    List: typeof import('./components/List.vue')['default']
    README: typeof import('./components/README.md')['default']
  }
}

export { }
